using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace LovelyGit.BLiteGenerators;

public sealed partial class BsonKeysGenerator
{
    private static bool IsPrimitiveLike(INamedTypeSymbol type)
    {
        if (type.SpecialType != SpecialType.None)
        {
            return true;
        }

        var name = type.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return name is "global::System.Guid" or "global::System.DateTime" or
            "global::System.DateTimeOffset" or "global::System.TimeSpan" or
            "global::System.Decimal";
    }

    private static bool IsCollectionType(INamedTypeSymbol type)
    {
        if (type.TypeKind == TypeKind.Array)
        {
            return true;
        }

        var name = type.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        if (name is "global::System.Collections.Generic.List<T>" or
            "global::System.Collections.Generic.IList<T>" or
            "global::System.Collections.Generic.IReadOnlyList<T>" or
            "global::System.Collections.Generic.ICollection<T>" or
            "global::System.Collections.Generic.IReadOnlyCollection<T>" or
            "global::System.Collections.Generic.IEnumerable<T>")
        {
            return true;
        }

        return type.AllInterfaces.Any(static item =>
            item.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ==
            "global::System.Collections.Generic.IEnumerable<T>");
    }

    private static string RenderDbContextPartial(INamedTypeSymbol dbContext, OrderedKeySet keys)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        var containingTypes = GetContainingTypes(dbContext);
        var namespaceName = dbContext.ContainingNamespace.IsGlobalNamespace
            ? null
            : dbContext.ContainingNamespace.ToDisplayString();

        if (namespaceName != null)
        {
            builder.Append("namespace ").Append(namespaceName).AppendLine(";");
            builder.AppendLine();
        }

        foreach (var containingType in containingTypes)
        {
            builder.Append("partial ").Append(GetTypeKind(containingType)).Append(' ')
                .Append(containingType.Name).AppendLine();
            builder.AppendLine("{");
        }

        builder.Append("partial ").Append(GetTypeKind(dbContext)).Append(' ')
            .Append(dbContext.Name).AppendLine();
        builder.AppendLine("{");
        builder.Append("    private static readonly string[] ")
            .Append(GetBsonKeysFieldName(dbContext)).AppendLine(" =");
        builder.AppendLine("    [");
        foreach (var key in keys.Keys)
        {
            builder.Append("        \"").Append(EscapeString(key)).AppendLine("\",");
        }
        builder.AppendLine("    ];");
        builder.AppendLine("}");
        foreach (var _ in containingTypes) builder.AppendLine("}");
        return builder.ToString();
    }

    private static ImmutableArray<INamedTypeSymbol> GetContainingTypes(INamedTypeSymbol type)
    {
        var types = ImmutableArray.CreateBuilder<INamedTypeSymbol>();
        for (var current = type.ContainingType; current != null; current = current.ContainingType)
        {
            types.Insert(0, current);
        }
        return types.ToImmutable();
    }

    private static string GetTypeKind(INamedTypeSymbol type) =>
        type.TypeKind == TypeKind.Struct ? "struct" : "class";

    private static string GetSymbolKey(INamedTypeSymbol type) =>
        type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string GetBsonKeysFieldName(INamedTypeSymbol dbContext) =>
        dbContext.Name == "GitRepoCacheDbContext" ? "CacheBsonKeys" : "AppBsonKeys";

    private static string GetHintName(INamedTypeSymbol type) =>
        type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .Replace("global::", string.Empty)
            .Replace('<', '_').Replace('>', '_').Replace('.', '_') + ".BsonKeys.g.cs";

    private static string EscapeString(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private sealed class OrderedKeySet
    {
        private readonly HashSet<string> _seen = new(StringComparer.Ordinal);
        private readonly List<string> _keys = new();
        public IReadOnlyList<string> Keys => _keys;

        public void Add(string key)
        {
            if (_seen.Add(key)) _keys.Add(key);
        }
    }
}
