import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type SettingDefinition = {
	name: string;
	type: string;
};

const __dirname = dirname(fileURLToPath(import.meta.url));
const frontendRoot = resolve(__dirname, "..");
const repoRoot = resolve(frontendRoot, "..");
const settingsSourcePath = resolve(
	repoRoot,
	"Services",
	"Settings",
	"SettingDefinition.cs",
);
const outputPath = resolve(frontendRoot, "src", "generated", "LovelyGit.SettingContracts.ts");

const source = readFileSync(settingsSourcePath, "utf8");
const definitions: SettingDefinition[] = [
	...source.matchAll(
		/public\s+static\s+readonly\s+SettingDefinition<(?<type>[^>]+)>\s+(?<name>\w+)\s*=/g,
	),
].map((match) => ({
	name: match.groups?.name ?? "",
	type: toTypeScriptType((match.groups?.type ?? "").trim()),
}));

if (definitions.length === 0) {
	throw new Error(`No SettingDefinition<T> declarations found in ${settingsSourcePath}`);
}

const settingValueMap = definitions
	.map(({ name, type }) => `\t${JSON.stringify(name)}: ${type};`)
	.join("\n");

const content = `/* THIS (.ts) FILE IS GENERATED BY scripts/generate-setting-contracts.ts */
/* eslint-disable */
/* tslint:disable */
import type {
\tCommsHubCommand,
\tCommsHubCommandType,
\tCommsHubSubCommandType,
\tEmptyCommandArguments,
} from "./ExpressThat.LovelyGit.Services.Hubs.Commands";

export type SettingValueMap = {
${settingValueMap}
};

export type TypedSetSettingsCommandArguments = {
\t[SettingName in keyof SettingValueMap]: {
\t\tsetting: SettingName;
\t\tvalue: SettingValueMap[SettingName];
\t};
}[keyof SettingValueMap];

export type TypedGetSettingsCommandArguments<
\tSettingName extends keyof SettingValueMap = keyof SettingValueMap,
> = {
\tsetting: SettingName;
};

type CommandInput<TArguments> = Omit<CommsHubCommand<TArguments>, "commandUniqueId">;

export type TypedSetSettingsCommandInput = Omit<
\tCommandInput<TypedSetSettingsCommandArguments>,
\t"arguments" | "commandType" | "subCommandType"
> & {
\tcommandType: "Settings";
\tsubCommandType: "Set";
\targuments: TypedSetSettingsCommandArguments;
};

export type TypedGetSettingsCommandInput<
\tSettingName extends keyof SettingValueMap = keyof SettingValueMap,
> = Omit<
\tCommandInput<TypedGetSettingsCommandArguments<SettingName>>,
\t"arguments" | "commandType" | "subCommandType"
> & {
\tcommandType: "Settings";
\tsubCommandType: "Get";
\targuments: TypedGetSettingsCommandArguments<SettingName>;
};

export type NonTypedSettingsCommandInput<TArguments = EmptyCommandArguments> =
\tCommandInput<TArguments> &
\t\t(
\t\t\t| { commandType: Exclude<CommsHubCommandType, "Settings"> }
\t\t\t| {
\t\t\t\t\tcommandType: "Settings";
\t\t\t\t\tsubCommandType?: Exclude<CommsHubSubCommandType, "Set" | "Get">;
\t\t\t\t}
\t\t);

export type TypedCommsHubCommandInput<TArguments = EmptyCommandArguments> =
\t| TypedSetSettingsCommandInput
\t| TypedGetSettingsCommandInput
\t| NonTypedSettingsCommandInput<TArguments>;
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, content);

function toTypeScriptType(type: string): string {
	const nullable = type.endsWith("?");
	const coreType = nullable ? type.slice(0, -1).trim() : type;
	const mapped = mapCoreType(coreType);
	return nullable ? `${mapped} | null` : mapped;
}

function mapCoreType(type: string): string {
	if (type === "string" || type === "Guid" || type === "DateTime" || type === "DateTimeOffset") {
		return "string";
	}

	if (
		type === "int" ||
		type === "long" ||
		type === "short" ||
		type === "byte" ||
		type === "float" ||
		type === "double" ||
		type === "decimal"
	) {
		return "number";
	}

	if (type === "bool") {
		return "boolean";
	}

	const arrayMatch = type.match(/^(?:IReadOnlyList|IList|List|IEnumerable|HashSet)<(.+)>$/);
	if (arrayMatch) {
		return `Array<${toTypeScriptType(arrayMatch[1].trim())}>`;
	}

	return "unknown";
}
