import {
	mkdirSync,
	readdirSync,
	readFileSync,
	statSync,
	writeFileSync,
} from "node:fs";
import { dirname, extname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type SettingDefinition = {
	name: string;
	sourceType: string;
	type: string;
};

type CommandContract = {
	name: string;
	argumentsType: string;
	commandType: string;
	responseType?: string;
};

type ServerEventContract = {
	eventName: string;
	payloadType: string;
};

const __dirname = dirname(fileURLToPath(import.meta.url));
const frontendRoot = resolve(__dirname, "..");
const projectRoot = resolve(frontendRoot, "..");
const servicesRoot = resolve(projectRoot, "Services");
const generatedRoot = resolve(frontendRoot, "src", "generated");
const outputPath = resolve(generatedRoot, "LovelyGit.CommandContracts.ts");

const settings = readSettings();
const commandContracts = readCommandContracts();
const serverEventContracts = readServerEventContracts();
const modules = new Map<string, Set<string>>();
const commandModule = findGeneratedModule([
	"CommsHubCommand",
	"CommsHubCommandType",
	"EmptyCommandArguments",
]);

for (const contract of commandContracts) {
	if (!isSettingsCommandWithTypedFrontendArguments(contract)) {
		registerTypeImports(contract.argumentsType);
	}
	if (contract.responseType && !isAllSettingsResponse(contract)) {
		registerTypeImports(contract.responseType);
	}
}
for (const setting of settings) {
	registerTypeImports(setting.sourceType);
}
for (const event of serverEventContracts) {
	registerTypeImports(event.payloadType);
}

const settingValueMap = settings
	.map(({ name, type }) => `\t${JSON.stringify(name)}: ${type};`)
	.join("\n");
const imports = renderImports();
const commandInputTypes = commandContracts
	.map(renderCommandInputType)
	.join("\n\n");
const commandInputUnion = commandContracts
	.map((contract) => `\t| ${commandInputTypeName(contract)}`)
	.join("\n");
const responseCases = commandContracts.map(renderResponseCase).join("");
const serverEventMap = serverEventContracts
	.map(
		(event) =>
			`\t${JSON.stringify(event.eventName)}: ${toTypeScriptType(event.payloadType)};`,
	)
	.join("\n");

const content = `/* THIS (.ts) FILE IS GENERATED BY scripts/generate-command-contracts.ts */
/* eslint-disable */
/* tslint:disable */
import type {
\tCommsHubCommand,
\tCommsHubCommandType,
\tEmptyCommandArguments,
} from "${commandModule}";
${imports}
export type SettingValueMap = {
${settingValueMap}
};

export type TypedSetSettingsCommandArguments = {
\t[SettingName in keyof SettingValueMap]: {
\t\tsetting: SettingName;
\t\tvalue: SettingValueMap[SettingName];
\t};
}[keyof SettingValueMap];

export type TypedGetSettingsCommandArguments<
\tSettingName extends keyof SettingValueMap = keyof SettingValueMap,
> = {
\tsetting: SettingName;
};

export type TypedSetMultipleSettingsCommandArguments = {
\tsettingValues: Partial<SettingValueMap>;
};

type CommandInput<TArguments> = Omit<CommsHubCommand<TArguments>, "commandUniqueId">;

${commandInputTypes}

export type TypedCommsHubCommandInput =
${commandInputUnion};

export type TypedSetSettingsCommandInput = Extract<
\tTypedCommsHubCommandInput,
\t{ arguments: TypedSetSettingsCommandArguments }
>;

export type TypedSetMultipleSettingsCommandInput = Extract<
\tTypedCommsHubCommandInput,
\t{ arguments: TypedSetMultipleSettingsCommandArguments }
>;

export type TypedGetSettingsCommandInput<
\tSettingName extends keyof SettingValueMap = keyof SettingValueMap,
> = Extract<
\tTypedCommsHubCommandInput,
\t{
\t\targuments: TypedGetSettingsCommandArguments<SettingName>;
\t}
>;

export type ResponseForCommand<TCommand extends TypedCommsHubCommandInput> =
${responseCases}\tunknown;

export type TypedCommandType = Extract<TypedCommsHubCommandInput["commandType"], CommsHubCommandType>;

export type ServerEventMap = {
${serverEventMap}
};

export type TypedServerEvent = keyof ServerEventMap;
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, content);

function readSettings(): SettingDefinition[] {
	const definitions = readFiles(servicesRoot)
		.flatMap((path) => [
			...readFileSync(path, "utf8").matchAll(
				/public\s+static\s+readonly\s+SettingDefinition<(?<type>[\w\s.,?<>]+)>\s+(?<name>\w+)\s*=/g,
			),
		])
		.map((match) => ({
			name: match.groups?.name ?? "",
			sourceType: (match.groups?.type ?? "").trim(),
			type: toTypeScriptType((match.groups?.type ?? "").trim()),
		}))
		.filter((definition) => definition.name.length > 0);

	if (definitions.length === 0) {
		throw new Error(
			`No SettingDefinition<T> declarations found under ${servicesRoot}`,
		);
	}

	return definitions;
}

function readCommandContracts(): CommandContract[] {
	const contracts = readFiles(servicesRoot).flatMap((path) =>
		readCommandContractsFromSource(readFileSync(path, "utf8")),
	);

	if (contracts.length === 0) {
		throw new Error(
			`No CommandResponder<TArguments> classes found under ${servicesRoot}`,
		);
	}

	return contracts;
}

function readServerEventContracts(): ServerEventContract[] {
	const contracts = readFiles(servicesRoot).flatMap((path) =>
		readServerEventContractsFromSource(readFileSync(path, "utf8")),
	);
	const byEventName = new Map<string, ServerEventContract>();
	for (const contract of contracts) {
		const existing = byEventName.get(contract.eventName);
		if (existing && existing.payloadType !== contract.payloadType) {
			throw new Error(
				`Conflicting payload types for SignalR event ${contract.eventName}: ${existing.payloadType} and ${contract.payloadType}`,
			);
		}

		byEventName.set(contract.eventName, contract);
	}

	return [...byEventName.values()].sort((left, right) =>
		left.eventName.localeCompare(right.eventName),
	);
}

function readServerEventContractsFromSource(source: string): ServerEventContract[] {
	const contracts: ServerEventContract[] = [];
	const sendRegex =
		/\.SendAsync\(\s*"(?<eventName>\w+)"\s*,\s*(?<payload>[^,\n)]+)/g;
	for (const match of source.matchAll(sendRegex)) {
		const eventName = match.groups?.eventName ?? "";
		if (!eventName || eventName === "Result") {
			continue;
		}

		const payload = (match.groups?.payload ?? "").trim();
		const payloadType = readPayloadType(source, match.index ?? 0, payload);
		if (!payloadType) {
			throw new Error(`Could not discover payload type for SignalR event ${eventName}`);
		}

		contracts.push({ eventName, payloadType });
	}

	return contracts;
}

function readPayloadType(
	source: string,
	sendIndex: number,
	payloadExpression: string,
): string | undefined {
	const newExpression = payloadExpression.match(/^new\s+(?<type>\w+)/);
	if (newExpression?.groups?.type) {
		return newExpression.groups.type;
	}

	if (!/^\w+$/.test(payloadExpression)) {
		return undefined;
	}

	const beforeSend = source.slice(0, sendIndex);
	const declarationRegex = new RegExp(
		`(?<type>\\w+(?:<[^;=]+>)?)\\s+${payloadExpression}\\s*(?:=|;)`,
		"g",
	);
	let payloadType: string | undefined;
	for (const declaration of beforeSend.matchAll(declarationRegex)) {
		payloadType = declaration.groups?.type?.trim();
	}

	return payloadType;
}

function readCommandContractsFromSource(source: string): CommandContract[] {
	const classRegex =
		/(?:public|internal)\s+(?:sealed\s+)?class\s+(?<name>\w+)\s*:\s*CommandResponder<(?<argumentsType>[^>]+)>/g;
	const matches = [...source.matchAll(classRegex)];

	return matches.map((match, index) => {
		const nextMatch = matches[index + 1];
		const body = source.slice(match.index, nextMatch?.index ?? source.length);
		const commandType = body.match(
			/command\.CommandType\s*==\s*CommsHubCommandType\.(?<commandType>\w+)/,
		)?.groups?.commandType;
		const responseType = readCommandResponseType(body);

		if (!commandType) {
			throw new Error(
				`Could not discover command type for ${match.groups?.name}`,
			);
		}

		return {
			name: match.groups?.name ?? commandType,
			argumentsType: (
				match.groups?.argumentsType ?? "EmptyCommandArguments"
			).trim(),
			commandType,
			responseType: responseType?.trim(),
		};
	});
}

function readCommandResponseType(source: string): string | undefined {
	const marker = "new CommandResponse<";
	const start = source.indexOf(marker);
	if (start === -1) {
		return undefined;
	}

	let depth = 1;
	let current = "";
	for (const char of source.slice(start + marker.length)) {
		if (char === "<") {
			depth++;
		}

		if (char === ">") {
			depth--;
			if (depth === 0) {
				return current.trim();
			}
		}

		current += char;
	}

	return undefined;
}

function renderCommandInputType(contract: CommandContract): string {
	if (isSingleSettingValueArgument(contract.argumentsType)) {
		return `export type ${commandInputTypeName(contract)} = Omit<
\tCommandInput<TypedSetSettingsCommandArguments>,
\t"arguments" | "commandType"
> & {
\tcommandType: "${contract.commandType}";
\targuments: TypedSetSettingsCommandArguments;
};`;
	}

	if (isMultipleSettingValueArgument(contract.argumentsType)) {
		return `export type ${commandInputTypeName(contract)} = Omit<
\tCommandInput<TypedSetMultipleSettingsCommandArguments>,
\t"arguments" | "commandType"
> & {
\tcommandType: "${contract.commandType}";
\targuments: TypedSetMultipleSettingsCommandArguments;
};`;
	}

	if (isSingleSettingLookupArgument(contract.argumentsType)) {
		return `export type ${commandInputTypeName(contract)}<
\tSettingName extends keyof SettingValueMap = keyof SettingValueMap,
> = Omit<
\tCommandInput<TypedGetSettingsCommandArguments<SettingName>>,
\t"arguments" | "commandType"
> & {
\tcommandType: "${contract.commandType}";
\targuments: TypedGetSettingsCommandArguments<SettingName>;
};`;
	}

	const hasArguments = contract.argumentsType !== "EmptyCommandArguments";
	return `export type ${commandInputTypeName(contract)} = Omit<
\tCommandInput<${toTypeScriptType(contract.argumentsType)}>,
\t"arguments" | "commandType"
> & {
\tcommandType: "${contract.commandType}";
\targuments${hasArguments ? "" : "?"}: ${toTypeScriptType(contract.argumentsType)};
};`;
}

function renderResponseCase(contract: CommandContract): string {
	const inputType = commandInputTypeName(contract);
	if (isSingleSettingLookupArgument(contract.argumentsType)) {
		return `\tTCommand extends ${inputType}<infer SettingName>
\t\t? SettingValueMap[SettingName]
\t\t:
`;
	}
	if (isAllSettingsResponse(contract)) {
		return `\tTCommand extends ${inputType}
\t\t? Partial<SettingValueMap>
\t\t:
`;
	}

	const responseType =
		isSingleSettingValueArgument(contract.argumentsType) ||
		isMultipleSettingValueArgument(contract.argumentsType)
			? "undefined"
			: contract.responseType
				? toTypeScriptType(contract.responseType)
				: "undefined";

	return `\tTCommand extends ${inputType}
\t\t? ${responseType}
\t\t:
`;
}

function commandInputTypeName(contract: CommandContract): string {
	return `${contract.name}CommandInput`;
}

function isSettingsCommandWithTypedFrontendArguments(
	contract: CommandContract,
): boolean {
	return (
		isSingleSettingLookupArgument(contract.argumentsType) ||
		isSingleSettingValueArgument(contract.argumentsType) ||
		isMultipleSettingValueArgument(contract.argumentsType)
	);
}

function isSingleSettingLookupArgument(typeName: string): boolean {
	const body = readRecordBody(typeName);
	return hasSettingProperty(body) && !hasValueJsonProperty(body);
}

function isSingleSettingValueArgument(typeName: string): boolean {
	const body = readRecordBody(typeName);
	return hasSettingProperty(body) && hasValueJsonProperty(body);
}

function isMultipleSettingValueArgument(typeName: string): boolean {
	return /Dictionary\s*<\s*Setting\s*,\s*string\s*>\s+SettingValueJsons\b/.test(
		readRecordBody(typeName),
	);
}

function isAllSettingsResponse(contract: CommandContract): boolean {
	return (
		contract.responseType?.replace(/\s/g, "") ===
		"Dictionary<Setting,JsonElement>"
	);
}

function hasSettingProperty(body: string): boolean {
	return /\bSetting\?\s+Setting\b/.test(body);
}

function hasValueJsonProperty(body: string): boolean {
	return /\bstring\?\s+ValueJson\b/.test(body);
}

function readRecordBody(typeName: string): string {
	for (const path of readFiles(servicesRoot)) {
		const source = readFileSync(path, "utf8");
		const match = source.match(
			new RegExp(
				`public\\s+record\\s+${typeName}\\s*\\{(?<body>[\\s\\S]*?)\\n\\s*\\}`,
			),
		);
		if (match?.groups?.body) {
			return match.groups.body;
		}
	}

	return "";
}

function readFiles(path: string): string[] {
	return readdirSync(path).flatMap((entry) => {
		const child = join(path, entry);
		if (statSync(child).isDirectory()) {
			return readFiles(child);
		}

		return extname(child) === ".cs" ? [child] : [];
	});
}

function registerTypeImports(type: string): void {
	for (const typeName of getNamedTypes(type)) {
		if (isTypeScriptPrimitive(typeName) || typeName === "JsonElement") {
			continue;
		}

		const module =
			typeName === "EmptyCommandArguments"
				? commandModule
				: findGeneratedModule([typeName]);
		const imports = modules.get(module) ?? new Set<string>();
		imports.add(typeName);
		modules.set(module, imports);
	}
}

function renderImports(): string {
	return [...modules.entries()]
		.filter(([module]) => module !== commandModule)
		.sort(([left], [right]) => left.localeCompare(right))
		.map(([module, names]) => {
			const sortedNames = [...names].sort();
			return `import type { ${sortedNames.join(", ")} } from "${module}";`;
		})
		.join("\n");
}

function findGeneratedModule(exportNames: string[]): string {
	for (const entry of readdirSync(generatedRoot)) {
		if (extname(entry) !== ".ts") {
			continue;
		}

		const path = join(generatedRoot, entry);
		const source = readFileSync(path, "utf8");
		if (exportNames.every((name) => hasExportedType(source, name))) {
			return `./${entry.slice(0, -extname(entry).length)}`;
		}
	}

	throw new Error(
		`Could not find generated module exporting: ${exportNames.join(", ")}`,
	);
}

function hasExportedType(source: string, typeName: string): boolean {
	return new RegExp(`\\bexport\\s+type\\s+${typeName}\\b`).test(source);
}

function toTypeScriptType(type: string): string {
	const nullable = type.endsWith("?");
	const coreType = nullable ? type.slice(0, -1).trim() : type;
	const mapped = mapCoreType(coreType);
	return nullable ? `${mapped} | null` : mapped;
}

function mapCoreType(type: string): string {
	const generic = parseGenericType(type);
	if (generic && isArrayType(generic.name)) {
		return `Array<${toTypeScriptType(generic.arguments[0])}>`;
	}
	if (generic && isDictionaryType(generic.name)) {
		return `Partial<Record<${toTypeScriptType(generic.arguments[0])}, ${toTypeScriptType(generic.arguments[1])}>>`;
	}

	if (
		type === "string" ||
		type === "Guid" ||
		type === "DateTime" ||
		type === "DateTimeOffset"
	) {
		return "string";
	}

	if (
		type === "int" ||
		type === "long" ||
		type === "short" ||
		type === "byte" ||
		type === "float" ||
		type === "double" ||
		type === "decimal"
	) {
		return "number";
	}

	if (type === "bool") {
		return "boolean";
	}

	if (type === "JsonElement") {
		return "unknown";
	}

	return type;
}

function getNamedTypes(type: string): string[] {
	const generic = parseGenericType(type);
	if (generic) {
		const genericName =
			isArrayType(generic.name) || isDictionaryType(generic.name)
				? []
				: [generic.name];
		return [
			...genericName,
			...generic.arguments.flatMap((argument) => getNamedTypes(argument)),
		];
	}

	const coreType = type.endsWith("?") ? type.slice(0, -1).trim() : type.trim();
	return [coreType];
}

function parseGenericType(
	type: string,
): { name: string; arguments: string[] } | null {
	const start = type.indexOf("<");
	if (start === -1 || !type.endsWith(">")) {
		return null;
	}

	return {
		name: type.slice(0, start).trim(),
		arguments: splitGenericArguments(type.slice(start + 1, -1)),
	};
}

function splitGenericArguments(argumentsText: string): string[] {
	const result: string[] = [];
	let depth = 0;
	let current = "";

	for (const char of argumentsText) {
		if (char === "<") {
			depth++;
		}

		if (char === ">") {
			depth--;
		}

		if (char === "," && depth === 0) {
			result.push(current.trim());
			current = "";
			continue;
		}

		current += char;
	}

	if (current.trim()) {
		result.push(current.trim());
	}

	return result;
}

function isArrayType(type: string): boolean {
	return ["IReadOnlyList", "IList", "List", "IEnumerable", "HashSet"].includes(
		type,
	);
}

function isDictionaryType(type: string): boolean {
	return ["Dictionary", "IDictionary", "IReadOnlyDictionary"].includes(type);
}

function isTypeScriptPrimitive(type: string): boolean {
	return [
		"string",
		"Guid",
		"DateTime",
		"DateTimeOffset",
		"int",
		"long",
		"short",
		"byte",
		"float",
		"double",
		"decimal",
		"bool",
	].includes(type);
}
